// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/delivery/http/todo/mapper.go

// Package todo is a generated GoMock package.
package todo

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	todo "github.com/kadirdeniz/golang-clean-architecture/internal/delivery/http/todo"
	entity "github.com/kadirdeniz/golang-clean-architecture/internal/domain/entity"
)

// MockMapper is a mock of Mapper interface.
type MockMapper struct {
	ctrl     *gomock.Controller
	recorder *MockMapperMockRecorder
}

// MockMapperMockRecorder is the mock recorder for MockMapper.
type MockMapperMockRecorder struct {
	mock *MockMapper
}

// NewMockMapper creates a new mock instance.
func NewMockMapper(ctrl *gomock.Controller) *MockMapper {
	mock := &MockMapper{ctrl: ctrl}
	mock.recorder = &MockMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapper) EXPECT() *MockMapperMockRecorder {
	return m.recorder
}

// ToEntity mocks base method.
func (m *MockMapper) ToEntity(dto *todo.CreateRequest) *entity.Todo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToEntity", dto)
	ret0, _ := ret[0].(*entity.Todo)
	return ret0
}

// ToEntity indicates an expected call of ToEntity.
func (mr *MockMapperMockRecorder) ToEntity(dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToEntity", reflect.TypeOf((*MockMapper)(nil).ToEntity), dto)
}

// ToEntityFromUpdate mocks base method.
func (m *MockMapper) ToEntityFromUpdate(existingTodo *entity.Todo, dto *todo.UpdateRequest) *entity.Todo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToEntityFromUpdate", existingTodo, dto)
	ret0, _ := ret[0].(*entity.Todo)
	return ret0
}

// ToEntityFromUpdate indicates an expected call of ToEntityFromUpdate.
func (mr *MockMapperMockRecorder) ToEntityFromUpdate(existingTodo, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToEntityFromUpdate", reflect.TypeOf((*MockMapper)(nil).ToEntityFromUpdate), existingTodo, dto)
}

// ToResponse mocks base method.
func (m *MockMapper) ToResponse(entity *entity.Todo) *todo.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToResponse", entity)
	ret0, _ := ret[0].(*todo.Response)
	return ret0
}

// ToResponse indicates an expected call of ToResponse.
func (mr *MockMapperMockRecorder) ToResponse(entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToResponse", reflect.TypeOf((*MockMapper)(nil).ToResponse), entity)
}
