// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/domain/usecase/todo_usecase.go

// Package todo is a generated GoMock package.
package todo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/kadirdeniz/golang-clean-architecture/internal/domain/entity"
)

// MockTodoUseCase is a mock of TodoUseCase interface.
type MockTodoUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTodoUseCaseMockRecorder
}

// MockTodoUseCaseMockRecorder is the mock recorder for MockTodoUseCase.
type MockTodoUseCaseMockRecorder struct {
	mock *MockTodoUseCase
}

// NewMockTodoUseCase creates a new mock instance.
func NewMockTodoUseCase(ctrl *gomock.Controller) *MockTodoUseCase {
	mock := &MockTodoUseCase{ctrl: ctrl}
	mock.recorder = &MockTodoUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoUseCase) EXPECT() *MockTodoUseCaseMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockTodoUseCase) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockTodoUseCaseMockRecorder) Count(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockTodoUseCase)(nil).Count), ctx)
}

// Create mocks base method.
func (m *MockTodoUseCase) Create(ctx context.Context, todo *entity.Todo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, todo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTodoUseCaseMockRecorder) Create(ctx, todo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTodoUseCase)(nil).Create), ctx, todo)
}

// Delete mocks base method.
func (m *MockTodoUseCase) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTodoUseCaseMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTodoUseCase)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockTodoUseCase) GetAll(ctx context.Context, limit, offset int) ([]*entity.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, limit, offset)
	ret0, _ := ret[0].([]*entity.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockTodoUseCaseMockRecorder) GetAll(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTodoUseCase)(nil).GetAll), ctx, limit, offset)
}

// GetByID mocks base method.
func (m *MockTodoUseCase) GetByID(ctx context.Context, id uint) (*entity.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTodoUseCaseMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTodoUseCase)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockTodoUseCase) Update(ctx context.Context, todo *entity.Todo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, todo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTodoUseCaseMockRecorder) Update(ctx, todo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTodoUseCase)(nil).Update), ctx, todo)
}
