// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/infrastructure/config/config.go

// Package infrastructure is a generated GoMock package.
package infrastructure

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	config "github.com/kadirdeniz/golang-clean-architecture/internal/infrastructure/config"
)

// MockConfig is a mock of Config interface.
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
}

// MockConfigMockRecorder is the mock recorder for MockConfig.
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance.
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return m.recorder
}

// GetAppConfig mocks base method.
func (m *MockConfig) GetAppConfig() config.AppConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppConfig")
	ret0, _ := ret[0].(config.AppConfig)
	return ret0
}

// GetAppConfig indicates an expected call of GetAppConfig.
func (mr *MockConfigMockRecorder) GetAppConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppConfig", reflect.TypeOf((*MockConfig)(nil).GetAppConfig))
}

// GetCORSConfig mocks base method.
func (m *MockConfig) GetCORSConfig() config.CORSConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCORSConfig")
	ret0, _ := ret[0].(config.CORSConfig)
	return ret0
}

// GetCORSConfig indicates an expected call of GetCORSConfig.
func (mr *MockConfigMockRecorder) GetCORSConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCORSConfig", reflect.TypeOf((*MockConfig)(nil).GetCORSConfig))
}

// GetDatabaseConfig mocks base method.
func (m *MockConfig) GetDatabaseConfig() config.DatabaseConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseConfig")
	ret0, _ := ret[0].(config.DatabaseConfig)
	return ret0
}

// GetDatabaseConfig indicates an expected call of GetDatabaseConfig.
func (mr *MockConfigMockRecorder) GetDatabaseConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseConfig", reflect.TypeOf((*MockConfig)(nil).GetDatabaseConfig))
}

// GetLoggingConfig mocks base method.
func (m *MockConfig) GetLoggingConfig() config.LoggingConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoggingConfig")
	ret0, _ := ret[0].(config.LoggingConfig)
	return ret0
}

// GetLoggingConfig indicates an expected call of GetLoggingConfig.
func (mr *MockConfigMockRecorder) GetLoggingConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoggingConfig", reflect.TypeOf((*MockConfig)(nil).GetLoggingConfig))
}

// GetServerConfig mocks base method.
func (m *MockConfig) GetServerConfig() config.ServerConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerConfig")
	ret0, _ := ret[0].(config.ServerConfig)
	return ret0
}

// GetServerConfig indicates an expected call of GetServerConfig.
func (mr *MockConfigMockRecorder) GetServerConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerConfig", reflect.TypeOf((*MockConfig)(nil).GetServerConfig))
}
