// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/kadirdeniz/golang-clean-architecture/internal/app"
	"github.com/kadirdeniz/golang-clean-architecture/internal/delivery/http"
	"github.com/kadirdeniz/golang-clean-architecture/internal/delivery/http/health"
	"github.com/kadirdeniz/golang-clean-architecture/internal/delivery/http/todo"
	"github.com/kadirdeniz/golang-clean-architecture/internal/domain/entity"
	"github.com/kadirdeniz/golang-clean-architecture/internal/domain/repository"
	"github.com/kadirdeniz/golang-clean-architecture/internal/infrastructure/config"
	"github.com/kadirdeniz/golang-clean-architecture/internal/infrastructure/datasource"
	"github.com/kadirdeniz/golang-clean-architecture/internal/infrastructure/validator"
	"github.com/kadirdeniz/golang-clean-architecture/internal/repository/postgres"
	"github.com/kadirdeniz/golang-clean-architecture/internal/use-case"
)

// Injectors from wire.go:

func InitializeApp() (app.App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	database := datasource.NewDatabase(configConfig)
	baseRepository := provideBaseRepository(database)
	todoRepository := postgres.NewTodoRepository(database, baseRepository)
	todoUseCase := usecase.NewTodoUseCase(todoRepository)
	mapper := todo.NewMapper()
	handler := todo.NewHandler(todoUseCase, mapper)
	router := todo.NewRouter(handler)
	healthHandler := health.NewHandler()
	healthRouter := health.NewRouter(healthHandler)
	httpRouter := http.NewRouter(router, healthRouter)
	appApp := app.NewApp(httpRouter.App(), database)
	return appApp, nil
}

// wire.go:

var infrastructureSet = wire.NewSet(config.NewConfig, datasource.NewDatabase, validator.NewValidator)

var repositorySet = wire.NewSet(postgres.NewTodoRepository, provideBaseRepository)

var useCaseSet = wire.NewSet(usecase.NewTodoUseCase)

var todoSet = wire.NewSet(todo.NewMapper, todo.NewHandler, todo.NewRouter)

var healthSet = wire.NewSet(health.NewHandler, health.NewRouter)

var appSet = wire.NewSet(
	infrastructureSet,
	repositorySet,
	useCaseSet,
	todoSet,
	healthSet, http.NewRouter, app.NewApp,
)

func provideBaseRepository(db datasource.Database) repository.BaseRepository[entity.Todo] {
	return postgres.NewBaseRepository[entity.Todo](db)
}
